import { MODULE_NAME } from './const'

const ActionType = {
	LOGIN: MODULE_NAME+'LOGIN',
	LOGIN_SUCCESSED: MODULE_NAME+'LOGIN_SUCCESSED',

	UPDATE_PASSWORD: MODULE_NAME+'UPDATE_PASSWORD',
	LOGOUT: MODULE_NAME+'LOGOUT',
	
	SET_ERROR: MODULE_NAME+'SET_ERROR'
}

export default ActionType