import { MODULE_NAME } from './const'

const ActionType = {
	LOGIN: MODULE_NAME+'LOGIN',
	LOGIN_SUCCESSED: MODULE_NAME+'LOGIN_SUCCESSED',

	LOGOUT: MODULE_NAME+'LOGOUT',
	
	SET_ERROR: MODULE_NAME+'SET_ERROR'
}

export default ActionType