import { MODULE_NAME } from './const'

const ActionType = {
	LOGIN: MODULE_NAME+'LOGIN',
	LOGIN_SUCCESSED: MODULE_NAME+'LOGIN_SUCCESSED',
	
	EDIT_LOGIN_FORM: MODULE_NAME+'EDIT_LOGIN_FORM',
	SET_ERROR: MODULE_NAME+'SET_ERROR'
}

export default ActionType