import { MODULE_NAME } from './const'

const ActionType = {
	BOOTSTRAP: 'BOOTSTRAP',
	BOOTSTRAP_SUCCESSED: MODULE_NAME+'BOOTSTRAP_SUCCESSED',

	CREATE_MATERIAL: MODULE_NAME+'CREATE_MATERIAL',
	CREATE_MATERIAL_SUCCESSED: MODULE_NAME+'CREATE_MATERIAL_SUCCESSED',
	
	SAVE_MATERIAL: MODULE_NAME+'SAVE_MATERIAL',
	SAVE_MATERIAL_SUCCESSED: MODULE_NAME+'SAVE_MATERIAL_SUCCESSED',

	BUY_MATERIAL: MODULE_NAME+'BUY_MATERIAL',
	BUY_MATERIAL_SUCCESSED: MODULE_NAME+'BUY_MATERIAL_SUCCESSED',
	
	SET_ERROR: MODULE_NAME+'SET_ERROR'
}

export default ActionType