import { MODULE_NAME } from './const'

const ActionType = {
	BOOTSTRAP: 'BOOTSTRAP',
	BOOTSTRAP_SUCCESSED: MODULE_NAME+'BOOTSTRAP_SUCCESSED',

	CREATE_ORDER: MODULE_NAME+'CREATE_ORDER',
	CREATE_ORDER_SUCCESSED: MODULE_NAME+'CREATE_ORDER_SUCCESSED',
	SAVE_ORDER: MODULE_NAME+'SAVE_ORDER',
	SAVE_ORDER_SUCCESSED: MODULE_NAME+'SAVE_ORDER_SUCCESSED',

	CREATE_ORDERED_ITEM: MODULE_NAME+'CREATE_ORDERED_ITEM',
	CREATE_ORDERED_ITEM_SUCCESSED: MODULE_NAME+'CREATE_ORDERED_ITEM_SUCCESSED',

	SAVE_ORDERED_ITEM: MODULE_NAME+'SAVE_ORDERED_ITEM',
	SAVE_ORDERED_ITEM_SUCCESSED: MODULE_NAME+'SAVE_ORDERED_ITEM_SUCCESSED',

	CHECKOUT_ORDER: MODULE_NAME+'CHECKOUT_ORDER',
	CHECKOUT_ORDER_SUCCESSED: MODULE_NAME+'CHECKOUT_ORDER_SUCCESSED',
	
	SELECT_ORDER: MODULE_NAME+'SELECT_ORDER',

	SYNCHRONIZE: MODULE_NAME+'SYNCHRONIZE',
	SOCKET_UPDATE: MODULE_NAME+'SOCKET_UPDATE',
	SET_ERROR: MODULE_NAME+'SET_ERROR'
}

export default ActionType