import { MODULE_NAME } from './const'

const ActionType = {
	BOOTSTRAP: 'BOOTSTRAP',
	BOOTSTRAP_SUCCESSED: MODULE_NAME+'BOOTSTRAP_SUCCESSED',

	CREATE_ORDER: MODULE_NAME+'CREATE_ORDER',
	CREATE_ORDER_SUCCESSED: MODULE_NAME+'CREATE_ORDER_SUCCESSED',
	SAVE_ORDER: MODULE_NAME+'SAVE_ORDER',
	SAVE_ORDER_SUCCESSED: MODULE_NAME+'SAVE_ORDER_SUCCESSED',

	EDIT_ORDER_FORM: MODULE_NAME+'EDIT_ORDER_FORM',

	ADD_ORDER_ITEM: MODULE_NAME+'ADD_ORDER_ITEM',
	EDIT_ORDER_ITEM: MODULE_NAME+'EDIT_ORDER_ITEM',
	REMOVE_ORDER_ITEM: MODULE_NAME+'REMOVE_ORDER_ITEM',
	CLEAR_ORDER_ITEM: MODULE_NAME+'CLEAR_ORDER_ITEM',

	CREATE_ORDERED_ITEM: MODULE_NAME+'CREATE_ORDERED_ITEM',
	CREATE_ORDERED_ITEM_SUCCESSED: MODULE_NAME+'CREATE_ORDERED_ITEM_SUCCESSED',

	SAVE_ORDERED_ITEM: MODULE_NAME+'SAVE_ORDERED_ITEM',
	SAVE_ORDERED_ITEM_SUCCESSED: MODULE_NAME+'SAVE_ORDERED_ITEM_SUCCESSED',

	SOCKET_UPDATE: MODULE_NAME+'SOCKET_UPDATE',
	SET_ERROR: MODULE_NAME+'SET_ERROR'
}

export default ActionType