import { MODULE_NAME } from './const'

const ActionType = {
	FETCH_DATA: MODULE_NAME+'FETCH_DATA',
	FETCH_DATA_SUCCESSED: MODULE_NAME+'FETCH_DATA_SUCCESSED',

	EDIT_FILTER: MODULE_NAME+'EDIT_FILTER',
	SET_ERROR: MODULE_NAME+'SET_ERROR'
}

export default ActionType