import { MODULE_NAME } from './const'

const ActionType = {
	BOOTSTRAP: 'BOOTSTRAP',
	BOOTSTRAP_SUCCESSED: MODULE_NAME+'BOOTSTRAP_SUCCESSED',

	CREATE_USER: MODULE_NAME+'CREATE_USER',
	CREATE_USER_SUCCESSED: MODULE_NAME+'CREATE_USER_SUCCESSED',
	
	SAVE_USER: MODULE_NAME+'SAVE_USER',
	SAVE_USER_SUCCESSED: MODULE_NAME+'SAVE_USER_SUCCESSED',
	
	EDIT_USER_FORM: MODULE_NAME+'EDIT_USER_FORM',
	SET_ERROR: MODULE_NAME+'SET_ERROR'
}

export default ActionType