import { MODULE_NAME } from './const'

const ActionType = {
	BOOTSTRAP: 'BOOTSTRAP',
	BOOTSTRAP_SUCCESSED: MODULE_NAME+'BOOTSTRAP_SUCCESSED',

	CREATE_USER: MODULE_NAME+'CREATE_USER',
	CREATE_USER_SUCCESSED: MODULE_NAME+'CREATE_USER_SUCCESSED',
	
	SAVE_USER: MODULE_NAME+'SAVE_USER',
	SAVE_USER_SUCCESSED: MODULE_NAME+'SAVE_USER_SUCCESSED',
	
	UPDATE_USER_ROLE: MODULE_NAME+'UPDATE_USER_ROLE',
	UPDATE_USER_ROLE_SUCCESSED: MODULE_NAME+'UPDATE_USER_ROLE_SUCCESSED',

	REMOVE_USER: MODULE_NAME+'REMOVE_USER',
	REMOVE_USER_SUCCESSED: MODULE_NAME+'REMOVE_USER_SUCCESSED',

	SET_ERROR: MODULE_NAME+'SET_ERROR'
}

export default ActionType